#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LainsaSciModelo;

namespace LainsaSciModelo	
{
	public partial class LainsaSci : OpenAccessContext, ILainsaSciUnitOfWork
	{
		private static string connectionStringName = @"DosimetriaCTX";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
		
		public LainsaSci()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public LainsaSci(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public LainsaSci(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public LainsaSci(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public LainsaSci(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<GrupoUsuario> GrupoUsuarios 
		{
			get
			{
				return this.GetAll<GrupoUsuario>();
			}
		}
		
		public IQueryable<Proceso> Procesos 
		{
			get
			{
				return this.GetAll<Proceso>();
			}
		}
		
		public IQueryable<Permiso> Permisos 
		{
			get
			{
				return this.GetAll<Permiso>();
			}
		}
		
		public IQueryable<Empresa> Empresas 
		{
			get
			{
				return this.GetAll<Empresa>();
			}
		}
		
		public IQueryable<Direccion> Direccions 
		{
			get
			{
				return this.GetAll<Direccion>();
			}
		}
		
		public IQueryable<Email> Emails 
		{
			get
			{
				return this.GetAll<Email>();
			}
		}
		
		public IQueryable<Telefono> Telefonos 
		{
			get
			{
				return this.GetAll<Telefono>();
			}
		}
		
		public IQueryable<UTPParametros> UTPParametros 
		{
			get
			{
				return this.GetAll<UTPParametros>();
			}
		}
		
		public IQueryable<Instalacion> Instalacions 
		{
			get
			{
				return this.GetAll<Instalacion>();
			}
		}
		
		public IQueryable<Operario> Operarios 
		{
			get
			{
				return this.GetAll<Operario>();
			}
		}
		
		public IQueryable<CarnetRadiologico> CarnetRadiologicos 
		{
			get
			{
				return this.GetAll<CarnetRadiologico>();
			}
		}
		
		public IQueryable<Dispositivo> Dispositivos 
		{
			get
			{
				return this.GetAll<Dispositivo>();
			}
		}
		
		public IQueryable<TipoDispositivo> TipoDispositivos 
		{
			get
			{
				return this.GetAll<TipoDispositivo>();
			}
		}
		
		public IQueryable<ModeloDispositivo> ModeloDispositivos 
		{
			get
			{
				return this.GetAll<ModeloDispositivo>();
			}
		}
		
		public IQueryable<PlantillaRevision> PlantillaRevisions 
		{
			get
			{
				return this.GetAll<PlantillaRevision>();
			}
		}
		
		public IQueryable<Campo> Campos 
		{
			get
			{
				return this.GetAll<Campo>();
			}
		}
		
		public IQueryable<TipoCampo> TipoCampos 
		{
			get
			{
				return this.GetAll<TipoCampo>();
			}
		}
		
		public IQueryable<Fabricante> Fabricantes 
		{
			get
			{
				return this.GetAll<Fabricante>();
			}
		}
		
		public IQueryable<AgenteExtintor> AgenteExtintors 
		{
			get
			{
				return this.GetAll<AgenteExtintor>();
			}
		}
		
		public IQueryable<Revision> Revisions 
		{
			get
			{
				return this.GetAll<Revision>();
			}
		}
		
		public IQueryable<DatosRevision> DatosRevisions 
		{
			get
			{
				return this.GetAll<DatosRevision>();
			}
		}
		
		public IQueryable<ResumenRevision> ResumenRevisions 
		{
			get
			{
				return this.GetAll<ResumenRevision>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mysql";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of LainsaSci.
		/// </summary>
		/// <param name="config">The BackendConfiguration of LainsaSci.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface ILainsaSciUnitOfWork : IUnitOfWork
	{
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<GrupoUsuario> GrupoUsuarios
		{
			get;
		}
		IQueryable<Proceso> Procesos
		{
			get;
		}
		IQueryable<Permiso> Permisos
		{
			get;
		}
		IQueryable<Empresa> Empresas
		{
			get;
		}
		IQueryable<Direccion> Direccions
		{
			get;
		}
		IQueryable<Email> Emails
		{
			get;
		}
		IQueryable<Telefono> Telefonos
		{
			get;
		}
		IQueryable<UTPParametros> UTPParametros
		{
			get;
		}
		IQueryable<Instalacion> Instalacions
		{
			get;
		}
		IQueryable<Operario> Operarios
		{
			get;
		}
		IQueryable<CarnetRadiologico> CarnetRadiologicos
		{
			get;
		}
		IQueryable<Dispositivo> Dispositivos
		{
			get;
		}
		IQueryable<TipoDispositivo> TipoDispositivos
		{
			get;
		}
		IQueryable<ModeloDispositivo> ModeloDispositivos
		{
			get;
		}
		IQueryable<PlantillaRevision> PlantillaRevisions
		{
			get;
		}
		IQueryable<Campo> Campos
		{
			get;
		}
		IQueryable<TipoCampo> TipoCampos
		{
			get;
		}
		IQueryable<Fabricante> Fabricantes
		{
			get;
		}
		IQueryable<AgenteExtintor> AgenteExtintors
		{
			get;
		}
		IQueryable<Revision> Revisions
		{
			get;
		}
		IQueryable<DatosRevision> DatosRevisions
		{
			get;
		}
		IQueryable<ResumenRevision> ResumenRevisions
		{
			get;
		}
	}
}
namespace LainsaSciModelo	
{
	public partial class Usuario
	{
		private int _usuarioId;
		public virtual int UsuarioId
		{
			get
			{
				return this._usuarioId;
			}
			set
			{
				this._usuarioId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _login;
		public virtual string Login
		{
			get
			{
				return this._login;
			}
			set
			{
				this._login = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private GrupoUsuario _grupoUsuario1;
		public virtual GrupoUsuario GrupoUsuario
		{
			get
			{
				return this._grupoUsuario1;
			}
			set
			{
				this._grupoUsuario1 = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class GrupoUsuario
	{
		private int _grupoUsuarioId;
		public virtual int GrupoUsuarioId
		{
			get
			{
				return this._grupoUsuarioId;
			}
			set
			{
				this._grupoUsuarioId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Permiso> _permisos = new List<Permiso>();
		public virtual IList<Permiso> Permisos
		{
			get
			{
				return this._permisos;
			}
		}
		
		private IList<Usuario> _usuarios1 = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios1;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Proceso
	{
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Proceso _procesoPadre;
		public virtual Proceso ProcesoPadre
		{
			get
			{
				return this._procesoPadre;
			}
			set
			{
				this._procesoPadre = value;
			}
		}
		
		private IList<Proceso> _procesos = new List<Proceso>();
		public virtual IList<Proceso> Procesos
		{
			get
			{
				return this._procesos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Permiso
	{
		private int _permisoId;
		public virtual int PermisoId
		{
			get
			{
				return this._permisoId;
			}
			set
			{
				this._permisoId = value;
			}
		}
		
		private bool _ver;
		public virtual bool Ver
		{
			get
			{
				return this._ver;
			}
			set
			{
				this._ver = value;
			}
		}
		
		private bool _crear;
		public virtual bool Crear
		{
			get
			{
				return this._crear;
			}
			set
			{
				this._crear = value;
			}
		}
		
		private bool _modificar;
		public virtual bool Modificar
		{
			get
			{
				return this._modificar;
			}
			set
			{
				this._modificar = value;
			}
		}
		
		private bool _especial;
		public virtual bool Especial
		{
			get
			{
				return this._especial;
			}
			set
			{
				this._especial = value;
			}
		}
		
		private GrupoUsuario _grupoUsuario;
		public virtual GrupoUsuario GrupoUsuario
		{
			get
			{
				return this._grupoUsuario;
			}
			set
			{
				this._grupoUsuario = value;
			}
		}
		
		private Proceso _proceso1;
		public virtual Proceso Proceso
		{
			get
			{
				return this._proceso1;
			}
			set
			{
				this._proceso1 = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Empresa
	{
		private int _empresaId;
		public virtual int EmpresaId
		{
			get
			{
				return this._empresaId;
			}
			set
			{
				this._empresaId = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _personaContacto;
		public virtual string PersonaContacto
		{
			get
			{
				return this._personaContacto;
			}
			set
			{
				this._personaContacto = value;
			}
		}
		
		private IList<Direccion> _direcciones = new List<Direccion>();
		public virtual IList<Direccion> Direcciones
		{
			get
			{
				return this._direcciones;
			}
		}
		
		private IList<Email> _emails = new List<Email>();
		public virtual IList<Email> Emails
		{
			get
			{
				return this._emails;
			}
		}
		
		private IList<Telefono> _telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this._telefonos;
			}
		}
		
		private IList<Instalacion> _instalaciones = new List<Instalacion>();
		public virtual IList<Instalacion> Instalaciones
		{
			get
			{
				return this._instalaciones;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
		private IList<TipoDispositivo> _tipoDispositivos = new List<TipoDispositivo>();
		public virtual IList<TipoDispositivo> TipoDispositivos
		{
			get
			{
				return this._tipoDispositivos;
			}
		}
		
		private IList<ModeloDispositivo> _modeloDispositivos = new List<ModeloDispositivo>();
		public virtual IList<ModeloDispositivo> ModeloDispositivos
		{
			get
			{
				return this._modeloDispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Direccion
	{
		private int _direccionId;
		public virtual int DireccionId
		{
			get
			{
				return this._direccionId;
			}
			set
			{
				this._direccionId = value;
			}
		}
		
		private string _poblacion;
		public virtual string Poblacion
		{
			get
			{
				return this._poblacion;
			}
			set
			{
				this._poblacion = value;
			}
		}
		
		private string _codPostal;
		public virtual string CodPostal
		{
			get
			{
				return this._codPostal;
			}
			set
			{
				this._codPostal = value;
			}
		}
		
		private string _provincia;
		public virtual string Provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				this._provincia = value;
			}
		}
		
		private string _pais;
		public virtual string Pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				this._pais = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private string _dirPostal;
		public virtual string DirPostal
		{
			get
			{
				return this._dirPostal;
			}
			set
			{
				this._dirPostal = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Email
	{
		private int _emailId;
		public virtual int EmailId
		{
			get
			{
				return this._emailId;
			}
			set
			{
				this._emailId = value;
			}
		}
		
		private string _mail;
		public virtual string Mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				this._mail = value;
			}
		}
		
		private bool _envio;
		public virtual bool Envio
		{
			get
			{
				return this._envio;
			}
			set
			{
				this._envio = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Telefono
	{
		private int _telefonoId;
		public virtual int TelefonoId
		{
			get
			{
				return this._telefonoId;
			}
			set
			{
				this._telefonoId = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class UTPParametros
	{
		private int _uTPParametrosId;
		public virtual int UTPParametrosId
		{
			get
			{
				return this._uTPParametrosId;
			}
			set
			{
				this._uTPParametrosId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _direccion;
		public virtual string Direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				this._direccion = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _mail;
		public virtual string Mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				this._mail = value;
			}
		}
		
		private decimal _maxDosisSuperficial;
		public virtual decimal MaxDosisSuperficial
		{
			get
			{
				return this._maxDosisSuperficial;
			}
			set
			{
				this._maxDosisSuperficial = value;
			}
		}
		
		private decimal _maxDosisSuperficalPeriodo;
		public virtual decimal MaxDosisSuperficalPeriodo
		{
			get
			{
				return this._maxDosisSuperficalPeriodo;
			}
			set
			{
				this._maxDosisSuperficalPeriodo = value;
			}
		}
		
		private decimal _maxDosisProfunda;
		public virtual decimal MaxDosisProfunda
		{
			get
			{
				return this._maxDosisProfunda;
			}
			set
			{
				this._maxDosisProfunda = value;
			}
		}
		
		private decimal _maxDosisProfundaPeriodo;
		public virtual decimal MaxDosisProfundaPeriodo
		{
			get
			{
				return this._maxDosisProfundaPeriodo;
			}
			set
			{
				this._maxDosisProfundaPeriodo = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Instalacion
	{
		private int _instalacionId;
		public virtual int InstalacionId
		{
			get
			{
				return this._instalacionId;
			}
			set
			{
				this._instalacionId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Direccion> _direcciones = new List<Direccion>();
		public virtual IList<Direccion> Direcciones
		{
			get
			{
				return this._direcciones;
			}
		}
		
		private IList<Email> _emails = new List<Email>();
		public virtual IList<Email> Emails
		{
			get
			{
				return this._emails;
			}
		}
		
		private IList<Telefono> _telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this._telefonos;
			}
		}
		
		private IList<Operario> _operarios = new List<Operario>();
		public virtual IList<Operario> Operarios
		{
			get
			{
				return this._operarios;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
		private IList<TipoDispositivo> _tipoDispositivos = new List<TipoDispositivo>();
		public virtual IList<TipoDispositivo> TipoDispositivos
		{
			get
			{
				return this._tipoDispositivos;
			}
		}
		
		private IList<ModeloDispositivo> _modeloDispositivos = new List<ModeloDispositivo>();
		public virtual IList<ModeloDispositivo> ModeloDispositivos
		{
			get
			{
				return this._modeloDispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Operario
	{
		private int _operarioId;
		public virtual int OperarioId
		{
			get
			{
				return this._operarioId;
			}
			set
			{
				this._operarioId = value;
			}
		}
		
		private string _dni;
		public virtual string Dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				this._dni = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private DateTime _fechaNacimiento;
		public virtual DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				this._fechaNacimiento = value;
			}
		}
		
		private Char _sexo;
		public virtual Char Sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				this._sexo = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private CarnetRadiologico _carnetRadiologico;
		public virtual CarnetRadiologico CarnetRadiologico
		{
			get
			{
				return this._carnetRadiologico;
			}
			set
			{
				this._carnetRadiologico = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class CarnetRadiologico
	{
		private int _carnetId;
		public virtual int CarnetId
		{
			get
			{
				return this._carnetId;
			}
			set
			{
				this._carnetId = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private DateTime _fechaEmision;
		public virtual DateTime fechaEmision
		{
			get
			{
				return this._fechaEmision;
			}
			set
			{
				this._fechaEmision = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Dispositivo
	{
		private int _dispositivoId;
		public virtual int DispositivoId
		{
			get
			{
				return this._dispositivoId;
			}
			set
			{
				this._dispositivoId = value;
			}
		}
		
		private DateTime _fechaFabricacion;
		public virtual DateTime FechaFabricacion
		{
			get
			{
				return this._fechaFabricacion;
			}
			set
			{
				this._fechaFabricacion = value;
			}
		}
		
		private DateTime _fechaCaducidad;
		public virtual DateTime FechaCaducidad
		{
			get
			{
				return this._fechaCaducidad;
			}
			set
			{
				this._fechaCaducidad = value;
			}
		}
		
		private string _posicion;
		public virtual string Posicion
		{
			get
			{
				return this._posicion;
			}
			set
			{
				this._posicion = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private DateTime _fechaInicioRevision;
		public virtual DateTime FechaInicioRevision
		{
			get
			{
				return this._fechaInicioRevision;
			}
			set
			{
				this._fechaInicioRevision = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _numeroIndustria;
		public virtual string NumeroIndustria
		{
			get
			{
				return this._numeroIndustria;
			}
			set
			{
				this._numeroIndustria = value;
			}
		}
		
		private DateTime _inicioRevisionPH;
		public virtual DateTime InicioRevisionPH
		{
			get
			{
				return this._inicioRevisionPH;
			}
			set
			{
				this._inicioRevisionPH = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
		private ModeloDispositivo _modeloDispositivo;
		public virtual ModeloDispositivo ModeloDispositivo
		{
			get
			{
				return this._modeloDispositivo;
			}
			set
			{
				this._modeloDispositivo = value;
			}
		}
		
		private Dispositivo _dispositivoPadre;
		public virtual Dispositivo DispositivoPadre
		{
			get
			{
				return this._dispositivoPadre;
			}
			set
			{
				this._dispositivoPadre = value;
			}
		}
		
		private Fabricante _fabricante;
		public virtual Fabricante Fabricante
		{
			get
			{
				return this._fabricante;
			}
			set
			{
				this._fabricante = value;
			}
		}
		
		private AgenteExtintor _agenteExtintor;
		public virtual AgenteExtintor AgenteExtintor
		{
			get
			{
				return this._agenteExtintor;
			}
			set
			{
				this._agenteExtintor = value;
			}
		}
		
		private IList<Dispositivo> _accesorios = new List<Dispositivo>();
		public virtual IList<Dispositivo> Accesorios
		{
			get
			{
				return this._accesorios;
			}
		}
		
		private IList<Revision> _revisiones = new List<Revision>();
		public virtual IList<Revision> Revisiones
		{
			get
			{
				return this._revisiones;
			}
		}
		
		private IList<ResumenRevision> _resumenesRevisones = new List<ResumenRevision>();
		public virtual IList<ResumenRevision> ResumenesRevisones
		{
			get
			{
				return this._resumenesRevisones;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class TipoDispositivo
	{
		private int _tipoId;
		public virtual int TipoId
		{
			get
			{
				return this._tipoId;
			}
			set
			{
				this._tipoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private int _caduca;
		public virtual int Caduca
		{
			get
			{
				return this._caduca;
			}
			set
			{
				this._caduca = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private IList<PlantillaRevision> _plantillaRevisions = new List<PlantillaRevision>();
		public virtual IList<PlantillaRevision> PlantillaRevisions
		{
			get
			{
				return this._plantillaRevisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class ModeloDispositivo
	{
		private int _modeloId;
		public virtual int ModeloId
		{
			get
			{
				return this._modeloId;
			}
			set
			{
				this._modeloId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class PlantillaRevision
	{
		private int _plantillaId;
		public virtual int PlantillaId
		{
			get
			{
				return this._plantillaId;
			}
			set
			{
				this._plantillaId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private string _tipoPeriodo;
		public virtual string TipoPeriodo
		{
			get
			{
				return this._tipoPeriodo;
			}
			set
			{
				this._tipoPeriodo = value;
			}
		}
		
		private int _numeroPeriodos;
		public virtual int NumeroPeriodos
		{
			get
			{
				return this._numeroPeriodos;
			}
			set
			{
				this._numeroPeriodos = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
		private IList<Campo> _campos = new List<Campo>();
		public virtual IList<Campo> Campos
		{
			get
			{
				return this._campos;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
		private IList<ResumenRevision> _resumenesRevisones = new List<ResumenRevision>();
		public virtual IList<ResumenRevision> ResumenesRevisones
		{
			get
			{
				return this._resumenesRevisones;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Campo
	{
		private int _campoId;
		public virtual int CampoId
		{
			get
			{
				return this._campoId;
			}
			set
			{
				this._campoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private int _posicion;
		public virtual int Posicion
		{
			get
			{
				return this._posicion;
			}
			set
			{
				this._posicion = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision1;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision1;
			}
			set
			{
				this._plantillaRevision1 = value;
			}
		}
		
		private TipoCampo _tipoCampo;
		public virtual TipoCampo TipoCampo
		{
			get
			{
				return this._tipoCampo;
			}
			set
			{
				this._tipoCampo = value;
			}
		}
		
		private IList<DatosRevision> _datosRevisions = new List<DatosRevision>();
		public virtual IList<DatosRevision> DatosRevisions
		{
			get
			{
				return this._datosRevisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class TipoCampo
	{
		private int _tipoId;
		public virtual int TipoId
		{
			get
			{
				return this._tipoId;
			}
			set
			{
				this._tipoId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Fabricante
	{
		private int _fabricanteId;
		public virtual int FabricanteId
		{
			get
			{
				return this._fabricanteId;
			}
			set
			{
				this._fabricanteId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class AgenteExtintor
	{
		private int _agenteExtintorId;
		public virtual int AgenteExtintorId
		{
			get
			{
				return this._agenteExtintorId;
			}
			set
			{
				this._agenteExtintorId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Revision
	{
		private int _revisionId;
		public virtual int RevisionId
		{
			get
			{
				return this._revisionId;
			}
			set
			{
				this._revisionId = value;
			}
		}
		
		private DateTime _fechaRevision;
		public virtual DateTime FechaRevision
		{
			get
			{
				return this._fechaRevision;
			}
			set
			{
				this._fechaRevision = value;
			}
		}
		
		private string _resultado;
		public virtual string Resultado
		{
			get
			{
				return this._resultado;
			}
			set
			{
				this._resultado = value;
			}
		}
		
		private string _observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private DateTime _fechaProgramada;
		public virtual DateTime FechaProgramada
		{
			get
			{
				return this._fechaProgramada;
			}
			set
			{
				this._fechaProgramada = value;
			}
		}
		
		private DateTime _fechaPlanificada;
		public virtual DateTime FechaPlanificada
		{
			get
			{
				return this._fechaPlanificada;
			}
			set
			{
				this._fechaPlanificada = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision;
			}
			set
			{
				this._plantillaRevision = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo Dispositivo
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private IList<DatosRevision> _datosRevisions = new List<DatosRevision>();
		public virtual IList<DatosRevision> DatosRevisions
		{
			get
			{
				return this._datosRevisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class DatosRevision
	{
		private int _datosId;
		public virtual int DatosId
		{
			get
			{
				return this._datosId;
			}
			set
			{
				this._datosId = value;
			}
		}
		
		private string _valor;
		public virtual string Valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				this._valor = value;
			}
		}
		
		private Campo _campo;
		public virtual Campo Campo
		{
			get
			{
				return this._campo;
			}
			set
			{
				this._campo = value;
			}
		}
		
		private Revision _revision;
		public virtual Revision Revision
		{
			get
			{
				return this._revision;
			}
			set
			{
				this._revision = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class ResumenRevision
	{
		private int _resumenRevisionId;
		public virtual int ResumenRevisionId
		{
			get
			{
				return this._resumenRevisionId;
			}
			set
			{
				this._resumenRevisionId = value;
			}
		}
		
		private DateTime _fechaInicio;
		public virtual DateTime FechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				this._fechaInicio = value;
			}
		}
		
		private DateTime _fechaSiguiente;
		public virtual DateTime FechaSiguiente
		{
			get
			{
				return this._fechaSiguiente;
			}
			set
			{
				this._fechaSiguiente = value;
			}
		}
		
		private DateTime _fechaUltima;
		public virtual DateTime FechaUltima
		{
			get
			{
				return this._fechaUltima;
			}
			set
			{
				this._fechaUltima = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo Dispositivo
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision;
			}
			set
			{
				this._plantillaRevision = value;
			}
		}
		
	}
}
#pragma warning restore 1591
